apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.ofac-sanctions
spec:
  tier: security
  order: 300
  selector: all()
  types:
  - Egress
  egress:
  - action: Deny
    destination:
      selector: threatfeed == "ofac"
  - action: Pass
